"""minify_schema

Revision ID: 58e1cf0af97a
Revises: e85e372fde7a
Create Date: 2026-02-11 15:24:44.464340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58e1cf0af97a'
down_revision: Union[str, None] = 'e85e372fde7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Drop eventmessage
    op.drop_table('eventmessage')

    # Step 2: Alter event (game_id to game_name)
    op.add_column('event', sa.Column('game_name', sa.String(), nullable=True))
    op.execute(
        "UPDATE event SET game_name = game.name FROM game WHERE event.game_id = game.id"
    )
    op.drop_constraint('event_game_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'plan_updated_at')
    op.drop_column('event', 'game_id')
    op.drop_column('event', 'plan_version')
    op.alter_column(
        'event',
        'game_name',
        existing_type=sa.String(),
        nullable=False
    )

    # Step 3: Drop game
    op.drop_table('game')

    # Step 4: Alter eventmembership
    externalsource_enum = postgresql.ENUM(
        'discord', name='externalsource', create_type=True
    )
    externalsource_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('eventmembership', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute(
        "UPDATE eventmembership SET id = gen_random_uuid() WHERE id IS NULL"
    )
    op.alter_column(
        'eventmembership',
        'id',
        existing_type=postgresql.UUID(as_uuid=True),
        nullable=False
    )
    op.drop_constraint('eventmembership_pkey', 'eventmembership', type_='primary')
    op.create_primary_key('eventmembership_pkey', 'eventmembership', ['id'])
    op.add_column(
        'eventmembership',
        sa.Column(
            'external_source',
            postgresql.ENUM('discord', name='externalsource', create_type=False),
            nullable=True
        )
    )
    op.add_column('eventmembership', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('eventmembership', sa.Column('display_name', sa.String(), nullable=True))
    op.alter_column(
        'eventmembership',
        'user_id',
        existing_type=postgresql.UUID(as_uuid=True),
        nullable=True
    )
    op.drop_column('eventmembership', 'confirmed_plan_version')

    # Step 5: Drop friendship
    op.drop_table('friendship')

    # Step 6: User table (keep autogenerated change)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)


def downgrade() -> None:
    # Reverse step 6
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])

    # Reverse step 5: Recreate friendship
    friendshipstatus_enum = postgresql.ENUM(
        'PENDING', 'ACCEPTED', name='friendshipstatus', create_type=True
    )
    friendshipstatus_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        'friendship',
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('friend_user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', name='friendshipstatus', create_type=False), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('responded_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('user_id', 'friend_user_id'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE', name='friendship_user_id_fkey'),
        sa.ForeignKeyConstraint(['friend_user_id'], ['user.id'], ondelete='CASCADE', name='friendship_friend_user_id_fkey')
    )

    # Reverse step 4: Alter eventmembership back
    op.execute("DELETE FROM eventmembership WHERE user_id IS NULL")
    op.add_column('eventmembership', sa.Column('confirmed_plan_version', sa.Integer(), nullable=True))
    op.alter_column(
        'eventmembership',
        'user_id',
        existing_type=postgresql.UUID(as_uuid=True),
        nullable=False
    )
    op.drop_column('eventmembership', 'display_name')
    op.drop_column('eventmembership', 'external_id')
    op.drop_column('eventmembership', 'external_source')
    op.drop_constraint('eventmembership_pkey', 'eventmembership', type_='primary')
    op.create_primary_key('eventmembership_pkey', 'eventmembership', ['event_id', 'user_id'])
    op.drop_column('eventmembership', 'id')
    postgresql.ENUM(name='externalsource').drop(op.get_bind(), checkfirst=True)

    # Reverse step 3: Recreate game
    op.create_table(
        'game',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('player_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # Insert a placeholder game so events can reference it (downgrade is lossy: original game data is gone)
    op.execute(
        "INSERT INTO game (id, name) VALUES ('00000000-0000-0000-0000-000000000001', 'Unknown')"
    )

    # Reverse step 2: Restore event columns
    op.add_column('event', sa.Column('plan_version', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('event', sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('event', sa.Column('plan_updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.execute(
        "UPDATE event SET game_id = '00000000-0000-0000-0000-000000000001'"
    )
    op.alter_column('event', 'game_id', nullable=False)
    op.create_foreign_key('event_game_id_fkey', 'event', 'game', ['game_id'], ['id'])
    op.drop_column('event', 'game_name')

    # Reverse step 1: Recreate eventmessage
    messagetype_enum = postgresql.ENUM('USER', 'SYSTEM', name='messagetype', create_type=True)
    messagetype_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        'eventmessage',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('message_type', postgresql.ENUM('USER', 'SYSTEM', name='messagetype', create_type=False), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE', name='eventmessage_event_id_fkey'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='eventmessage_user_id_fkey')
    )
