"""initial migration

Revision ID: 8b2f4a69b0ae
Revises: 
Create Date: 2026-01-12 02:02:18.226140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b2f4a69b0ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types for PostgreSQL
    eventstatus_enum = sa.Enum('PLANNING', 'CONFIRMED', 'CANCELLED', name='eventstatus', create_type=True)
    eventstatus_enum.create(op.get_bind(), checkfirst=True)
    
    friendshipstatus_enum = sa.Enum('PENDING', 'ACCEPTED', name='friendshipstatus', create_type=True)
    friendshipstatus_enum.create(op.get_bind(), checkfirst=True)
    
    membershiprole_enum = sa.Enum('HOST', 'ATTENDEE', name='membershiprole', create_type=True)
    membershiprole_enum.create(op.get_bind(), checkfirst=True)
    
    membershipstatus_enum = sa.Enum('PENDING', 'ACCEPTED', name='membershipstatus', create_type=True)
    membershipstatus_enum.create(op.get_bind(), checkfirst=True)
    
    messagetype_enum = sa.Enum('USER', 'SYSTEM', name='messagetype', create_type=True)
    messagetype_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=True),
    sa.Column('location_or_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'CONFIRMED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('plan_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendship',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('friend_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='friendshipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_user_id')
    )
    op.create_table('eventmembership',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('HOST', 'ATTENDEE', name='membershiprole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='membershipstatus'), nullable=False),
    sa.Column('confirmed_plan_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('eventmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sa.Enum('USER', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventmessage')
    op.drop_table('eventmembership')
    op.drop_table('friendship')
    op.drop_table('event')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('game')
    
    # Drop enum types for PostgreSQL
    sa.Enum(name='messagetype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='membershipstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='membershiprole').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='friendshipstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='eventstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
